### ISSUE TITLE
deadlock creating participant

### ISSUE THREAD

**Issue by dirk-thomas** [eProsima/Fast-RTPS#104]
While debugging some of our failing / flaky tests I ran into the following case (multiple time) where the call to `eprosima::fastrtps::Domain::createParticipant` blocked indefinitely. This is with the current [master](https://github.com/eProsima/Fast-RTPS/commit/f978ca4563cbea1e318308edb4148219a44d2da9) of FastRPTS on Ubuntu Xenial. I hope the following stacktrace is helpful:

```
#0  __lll_lock_wait ()
    at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007ffff7136dbd in __GI___pthread_mutex_lock (mutex=0x9252e0)
    at ../nptl/pthread_mutex_lock.c:80
#2  0x00007ffff7375e8c in __gthread_mutex_lock (__mutex=0x9252e0)
    at /usr/include/x86_64-linux-gnu/c++/5/bits/gthr-default.h:748
#3  0x00007ffff737ef14 in std::mutex::lock (this=0x9252e0)
    at /usr/include/c++/5/mutex:135
#4  0x00007ffff73845f8 in std::lock_guard<std::mutex>::lock_guard (this=0x7fffffff5800, __m=...)
    at /usr/include/c++/5/mutex:386
#5  0x00007ffff55c0a58 in eprosima::fastrtps::rtps::MessageReceiver::associateEndpoint (this=0x925240, to_add=0x10b3840)
    at .../eProsima/Fast-RTPS/src/cpp/rtps/messages/MessageReceiver.cpp:91
#6  0x00007ffff55d637f in eprosima::fastrtps::rtps::RTPSParticipantImpl::assignEndpoint2LocatorList (this=0xbfa9c0, endp=0x10b3840, list=...)
    at .../eProsima/Fast-RTPS/src/cpp/rtps/participant/RTPSParticipantImpl.cpp:797
#7  0x00007ffff55d601b in eprosima::fastrtps::rtps::RTPSParticipantImpl::assignEndpointListenResources (this=0xbfa9c0, endp=0x10b3840)
    at .../eProsima/Fast-RTPS/src/cpp/rtps/participant/RTPSParticipantImpl.cpp:731
#8  0x00007ffff55d6142 in eprosima::fastrtps::rtps::RTPSParticipantImpl::createAndAssociateReceiverswithEndpoint (this=0xbfa9c0, pend=0x10b3840)
    at .../eProsima/Fast-RTPS/src/cpp/rtps/participant/RTPSParticipantImpl.cpp:757
#9  0x00007ffff55d5b5a in eprosima::fastrtps::rtps::RTPSParticipantImpl::createReader (this=0xbfa9c0, ReaderOut=0x7fffffff5c88, param=..., hist=0xde09d0, listen=0x10b3710, entityId=..., isBuiltin=true, enable=true)
    at .../eProsima/Fast-RTPS/src/cpp/rtps/participant/RTPSParticipantImpl.cpp:636
#10 0x00007ffff56419a0 in eprosima::fastrtps::rtps::WLP::createEndpoints (this=0x106ba80)
    at .../eProsima/Fast-RTPS/src/cpp/rtps/builtin/liveliness/WLP.cpp:133
#11 0x00007ffff5641574 in eprosima::fastrtps::rtps::WLP::initWL (this=0x106ba80, p=0xbfa9c0)
    at .../eProsima/Fast-RTPS/src/cpp/rtps/builtin/liveliness/WLP.cpp:81
#12 0x00007ffff56221d0 in eprosima::fastrtps::rtps::BuiltinProtocols::initBuiltinProtocols (this=0x926400, p_part=0xbfa9c0, attributes=...)
    at .../eProsima/Fast-RTPS/src/cpp/rtps/builtin/BuiltinProtocols.cpp:78
#13 0x00007ffff55d4155 in eprosima::fastrtps::rtps::RTPSParticipantImpl::RTPSParticipantImpl (this=0xbfa9c0, PParam=..., guidP=..., par=0x73bd70, plisten=0xbfa8f0)
    at .../eProsima/Fast-RTPS/src/cpp/rtps/participant/RTPSParticipantImpl.cpp:333
#14 0x00007ffff55dc2c5 in eprosima::fastrtps::rtps::RTPSDomain::createParticipant (PParam=..., listen=0xbfa8f0)
    at .../eProsima/Fast-RTPS/src/cpp/rtps/RTPSDomain.cpp:145
#15 0x00007ffff55de825 in eprosima::fastrtps::Domain::createParticipant (att=..., listen=0x0)
    at .../eProsima/Fast-RTPS/src/cpp/Domain.cpp:118
#16 0x00007ffff7377586 in rmw_create_node (name=0x4187c3 "test_graph_node", namespace_=0x7ffff79d098a "/", domain_id=68)
    at .../rmw_fastrtps/rmw_fastrtps_cpp/src/functions.cpp:649
```

**Comment by richiware** [comment]
@dirk-thomas Do you still have this problem? I think new version solves it.

**Comment by dirk-thomas** [comment]
We can close it for now and I will comment if I see this happening again.
